version: '3.8'

services:
  localdb:
    container_name: postgres-dev
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    restart: always
    environment:
      - POSTGRES_USER=db_dev
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dev

  testdb:
    container_name: postgres-test
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=db_test
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test
